service: starwars

package:
  individually: true
  exclude:
    - datos_mysql/**
    - .git/**
provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: production
  region: us-east-1
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 300
  

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}
    package:
      exclude:
        - node_modules/**
        - .git/** 
        - test/** 
plugins:
  - serverless-jetpack
  - serverless-offline
  